#define PACKAGE_NAME "hopes"
#define PACKAGE_TARNAME "hopes"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "hopes 1.0"
#define PACKAGE_BUGREPORT "whuzhshj@163.com"
#define PACKAGE "hopes"
#define VERSION "1.0"
#define HAVE_LIBM 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_UNISTD_H 1
#define HAVE__BOOL 1
#define HAVE_STDBOOL_H 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define HAVE_STRFTIME 1
#define HAVE_FLOOR 1
#define HAVE_MODF 1
#define HAVE_POW 1
#define HAVE_SQRT 1
