# 
#LABELS: time_system:NONE:time_system:NONE
#OBJ_time_system ch2jd   ch2sec  ch2cal  ch2dp   ch2dpx  ch2int
#OBJ_time_system cal2gps cal2jd  cal2ch  gps2cal gps2utc gpslpsec 
#OBJ_time_system cal2sec caschg  date2j  int2ch  j2date
#OBJ_time_system jd2cal  jd2cald jd2sec  jdref   leapsec 
#OBJ_time_system sec2jd  sec2jdd sec2cal  sec2mjd sec2ch  taiutc   utc2gps 
# 
